[package]
name = "PhotoManager"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
inquire = "0.7.5"
serde = { version = "1.0.205", features = ["derive"] }
toml = "0.8.19"
